### ISSUE TITLE
Bootstrap Clash

### ISSUE THREAD

**Issue by shaneseaton** [tsega/meteor-paginator#4]
This was exactly what I was looking for. Simple client side Collection paging.

Unfortunately, your included bootstrap version clashed with mine (I am using a bootswatch version). It would be totally awesome if you could yank the bootstrap dependency from you package and ask the user to install one of there own. It would make your package more flexible. 

Maybe you know of a way I can override you bootstrap version???

**Comment by tsega** [comment]
@shaneseaton glad this package is of use to you, I think I should remove the bootstrap dependency since there are many versions of bootstrap one can use this with. I'll change that right now.

**Comment by tsega** [comment]
Please update your package to v1.1.7 and let me know how it goes.

**Comment by shaneseaton** [comment]
Thanks, this is great
